### ISSUE TITLE
[sign -up] issues faced while using  http://techspace.club/infox16/signup.php

### ISSUE THREAD

**Issue by iamsarthak** [prabhanshuguptagit/infox16#9]
1. Use javascript to check whether the input given by the user in the 'mobile number' section is a number without moving him/her to the next blank screen.
2. Use javascript to match the input password given in the 'password' and 're-type password' fields as soon as the user starts typing the re-type password.

Rest everything looks great

**Comment by iamsarthak** [comment]
for password matching take this as ref http://jsfiddle.net/rpP4K/

if you are unable to incorporate this then do tell me i will help if u want

**Comment by rjrajivjha** [comment]
the code is all yours, develop it, create a pull request. We will merge if its all okay. That's the procedure to contribute.
